#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from PyQt4 import QtGui, QtCore
import mainwindow
import canchannel

class Main(QtGui.QMainWindow, canchannel.CanChannel):
    def __init__(self):
        super(Main, self).__init__()
        self.ui = mainwindow.Ui_MainWindow()
        self.ui.setupUi(self)
        self.show()
        self.open()

    @QtCore.pyqtSlot()
    def on_action_exit_triggered(self):
        #QtGui.qApp.quit()
        self.close()

    @QtCore.pyqtSlot()
    def on_action_open_triggered(self):
        self.log('open')

    def log(self, msg):
        self.ui.textEdit.insertPlainText(str(msg))
        self.ui.textEdit.insertPlainText('\n')

def main():
    app = QtGui.QApplication(sys.argv)
    mw = Main()
    #ch = canchannel.CanChannel(logger=mw)
    #ch.open()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
