#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from PyQt4 import QtGui, QtCore
import mainwindow

class Main(QtGui.QMainWindow):
    def __init__(self):
        super(Main, self).__init__()
        self.ui = mainwindow.Ui_MainWindow()
        self.ui.setupUi(self)
        self.show()

    @QtCore.pyqtSlot()
    def on_action_exit_triggered(self):
        #QtGui.qApp.quit()
        self.close()

    @QtCore.pyqtSlot()
    def on_action_open_triggered(self):
        print 'open'
        txt = open('foo').read()


def main():
    import sys
    app = QtGui.QApplication(sys.argv)
    mw = Main()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
