#!/usr/bin/env python
import sys
import time
import kvaser
import canmsg

if len(sys.argv) > 1:
    cnt = int(sys.argv[1])
else:
    cnt = 10

ch = kvaser.KvaserCanChannel(0)


for i in range(cnt):
    m = canmsg.CanMsg()
    m.extended = False
    m.addr = 55
    m.data = [(i >> 28) & 0xFF
             , (i >> 16) & 0xFF
             , (i >> 8) & 0xFF
             , i & 0xFF]
    ch.write(m)

time.sleep(0.1)

